### createStudent

POST  http://localhost:3003/student/createStudent
Content-Type: application/json

{  
    "name": "Chaves", 
    "email": "chaves@email.com", 
    "birthday_date": "1929/02/21", 
    "hobbies": "Futebol, comer sanduiche de presunto, dormir no barril e falar isso isso isso."
}


### createTeacher

POST  http://localhost:3003/teacher/createTeacher
Content-Type: application/json

{  
    "name": "Dona Florinda", 
    "email": "florinda@email.com",
    "birthday_date": "1949/02/08"
}


### createClass

POST  http://localhost:3003/class/createClass
Content-Type: application/json

{  
    "name": "Era um vez", 
    "start_date": "2021/03/03",
    "finish_date": "2021/09/10",
    "module": "second",
    "class_type": "integral"
}


### postStudentToClass

POST  http://localhost:3003/student/class
Content-Type: application/json

{  
   "class_id": "6b04aa32-84fa-476e-affc-f3587e363cc4",
	"id": "4a6cbccd-dda4-4037-bbbf-b77b57a6e84d"
}


### getAgeStudentById

GET  http://localhost:3003/studet/015f22d2-2ad2-4253-b3d9-a91d6d335f4e
